# Generated by Django 4.1.6 on 2023-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine1mg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('imglink', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('sideeffect', models.CharField(blank=True, max_length=2000, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('howtouse', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('medlink', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineNetMeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('imglink', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('sideeffect', models.CharField(blank=True, max_length=2000, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('howtouse', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('medlink', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePharmEasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('imglink', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('sideeffect', models.CharField(blank=True, max_length=2000, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('howtouse', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('medlink', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('medicine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('website_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
