# Generated by Django 4.1.6 on 2023-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscrapperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('medicine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('website_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
