# Generated by Django 4.1.6 on 2023-02-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscrapperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine1mg',
            name='medlink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicinenetmeds',
            name='medlink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicinepharmeasy',
            name='medlink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
